apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: vault
    releaseName: opf
    repo: https://helm.releases.hashicorp.com
    includeCRDs: true
    valuesInline:
      global:
        openshift: true
      injector:
        enabled: false
      ui:
        enabled: true
      server:
        ha:
          enabled: true
          raft:
            enabled: true
        route:
          enabled: true
